### ISSUE TITLE
使用pyinstaller编译后报错

### ISSUE THREAD

**Issue by tpishere** [Hidove/aliyundrive-uploader#12]
[![gOCI6H.png](https://z3.ax1x.com/2021/05/22/gOCI6H.png)](https://imgtu.com/i/gOCI6H)
config.json文件被指定到了`/tmp/_MEIkpV1ri/config.json`这个路径

**Comment by Hidove** [comment]
编译后读取的目录还是py文件的目录而不是可执行文件的目录，得改一下才行
