### ISSUE TITLE
预编译版本 上传报错

### ISSUE THREAD

**Issue by a-kami** [Hidove/aliyundrive-uploader#14]
{'code': 'InvalidParameter.FileId', 'message': 'The input parameter file_id is not valid. for cpp path domain file_id is required'}
{'drive_id': 'drive_id', 'file_id': None, 'upload_id': None}

debian 10

**Comment by Hidove** [comment]
No problem.你的config.json配置有问题
![image](https://user-images.githubusercontent.com/42663943/120198631-e7630600-c254-11eb-9f7e-f20290aa87dc.png)
