### ISSUE TITLE
无法使用绝对路径上传

### ISSUE THREAD

**Issue by auqhjjqdo** [Hidove/aliyundrive-uploader#15]
![image](https://user-images.githubusercontent.com/56216884/124371163-b8a3d980-dcb1-11eb-8b6a-9064b5018fb7.png)

单文件上传如果是传入绝对路径参数，config里的FILE_PATH为空时会出现如图的报错，文件路径变成了脚本的运行目录，如果将FILE_PATH改成文件路径就能正常上传

所以这个FILE_PATH有什么作用吗，能否直接通过传入的路径参数修改该值？如果每次上传都要填一遍FILE_PATH岂不是很麻烦

**Comment by Hidove** [comment]
已经OK了，之前忘了替换`FILE_PATH`为`DATA['FILE_PATH']`导致无法读取命令行参数里的目录了

**Comment by auqhjjqdo** [comment]
测试已修复bug
