### ISSUE TITLE
后台运行机制代码存在bug

### ISSUE THREAD

**Issue by Nuaalzy** [Hidove/aliyundrive-uploader#17]
Client.py文件中，第77行判断是否有后台运行参数时，如果存在，立刻删除会导致后面数组访问越界，原始代码如下。

77    def init_command_line_parameter(self):
78        for k in range(len(sys.argv)):
79            if sys.argv[k] == '--resident' or sys.argv[k] == '-r':
80                DATA['config']['RESIDENT'] = True
81                del sys.argv[k]

报错情况为：
Traceback (most recent call last):
  File "/root/aliyundrive-uploader-master/main.py", line 26, in <module>
    client.init_command_line_parameter()
  File "/root/aliyundrive-uploader-master/Client.py", line 77, in init_command_line_parameter
    if sys.argv[k] == '--resident' or sys.argv[k] == '-r':
IndexError: list index out of range

修改建议，增加标识位，for循环后再删除，如
        label = -1
        for k in range(len(sys.argv)):
            if sys.argv[k] == '--resident' or sys.argv[k] == '-r':
                DATA['config']['RESIDENT'] = True
                label = k
        if label>-1:
            del sys.argv[label]

**Comment by aoaostar** [comment]
@Nuaalzy 已经修复了，感谢反馈

**Comment by Nuaalzy** [comment]
常驻运行仍然存在问题：
1.如果开启常驻运行，或者带-r参数时，不会添加新的任务，只会运行之前未完成添加到数据库的任务。只有在不开启常驻运行或者不带-r参数时才会添加任务。

main.py 第30行
`
# 是否常驻运行
if not DATA['config']['RESIDENT']:
    for v in client.tasks:
        tmp = DATA['task_template'].copy()
        tmp.update({
            "filepath": v,
            "realpath": DATA['config']['FILE_PATH'] + v,
            "create_time": get_timestamp(),
        })
        find = db.table('task').where('filepath=? and realpath=?', (tmp['filepath'], tmp['realpath'],)).find()
        if find:
            print_info('【%s】已存在任务队列中，跳过' % tmp['filepath'])
        else:
            create_task(tmp)
`

2.上传是会将配置文件中的网盘地址与上传文件或目录拼接为新地址，创建到网盘中去。例如，配置文件中设置上传目录为“网盘”，上传的文件目录为“目录一”，上传到网盘时会创建文件“网盘目录一”的文件，而不是放到网盘文件夹下。
main.py  第36行
"realpath": DATA['config']['FILE_PATH'] + v,

**Comment by aoaostar** [comment]
1.这个我设定的就是这样的，以便于web端添加任务

2.这个是会将本地`图片`目录下的文件上传到`网盘目录/图片`目录下，上传单文件就是在`网盘目录`里
https://github.com/Hidove/aliyundrive-uploader/blob/dd355e49d5f05394930f68d3a14aebc2747a9624/Client.py#L109

**Comment by zsbai** [comment]
> 1.这个我设定的就是这样的，以便于web端添加任务
> 
> 2.这个是会将本地`图片`目录下的文件上传到`网盘目录/图片`目录下，上传单文件就是在`网盘目录`里
> 
> https://github.com/Hidove/aliyundrive-uploader/blob/dd355e49d5f05394930f68d3a14aebc2747a9624/Client.py#L109

使用宝塔插件的时候，需要上传/xxxx/path/下的文件，上传到网盘/1/，他会上传到网盘根目录，/1path/下，会创建一个1path的新文件夹
