### ISSUE TITLE
请问使用常驻命令不管用怎么办呢？

### ISSUE THREAD

**Issue by xiaocainiao2020** [Hidove/aliyundrive-uploader#22]
使用python3 main.py --resident或者python3 main.py -r，程序还是过了一两秒自动结束了，并没有常驻，这是什么原因呢？

**Comment by aoaostar** [comment]
OK了，问题所在，定时刷新token导致的配置失效了
https://github.com/Hidove/aliyundrive-uploader/blob/da15bfc703ee597e5233cd795969b85af163b9ae/main.py#L71-L93
https://github.com/Hidove/aliyundrive-uploader/blob/da15bfc703ee597e5233cd795969b85af163b9ae/AliyunDrive.py#L110-L111
https://github.com/Hidove/aliyundrive-uploader/blob/da15bfc703ee597e5233cd795969b85af163b9ae/common.py#L98-L108
