### ISSUE TITLE
出现重复上传的问题

### ISSUE THREAD

**Issue by xiaocainiao2020** [Hidove/aliyundrive-uploader#23]
发现上传到阿里云盘里的文件重复了，而且两个文件名还是一样的，按理说一个文件夹应该不能两个完全一样文件名的文件，作者大大能看看这是哪里的问题吗？

**Comment by aoaostar** [comment]
这个问题和 #7 差不多，你配置文件里设置覆盖就行了

**Comment by xiaocainiao2020** [comment]
> 这个问题和#7差不多，你配置文件里设置覆盖就行了

哦好的，但是我还有个疑问就是，如果检测到有这个文件了，不是应该直接跳过上传吗？是现在还没有开发这个功能吗？

**Comment by aoaostar** [comment]
> > 这个问题和#7差不多，你配置文件里设置覆盖就行了
> 
> 哦好的，但是我还有个疑问就是，如果检测到有这个文件了，不是应该直接跳过上传吗？是现在还没有开发这个功能吗？

不是，这个阿里云盘自己有这个判断：

1. `auto_rename`：如果存在相同文件，会将第二次上传的同名文件重命名为XXX(2)；
2. `auto_rename：refuse`：如果存在相同文件，会返回上次失败，因为有同名文件的信息

我对于这个，做的是如下操作
`config.jso`n中`overwrite`参数为`false`时，即默认第一种，同名文件重命名
`overwrite`参数为`true`时，删除同名文件到回收站，然后重新把新的文件上传上去。
