### ISSUE TITLE
上传文件时报错

### ISSUE THREAD

**Issue by gifyic** [Hidove/aliyundrive-uploader#24]
{'code': 'InvalidParameter.ContentHash', 'message': 'The input parameter content_hash is not valid. file content hash is not matched with content_hash in complete file request'}

**Comment by aoaostar** [comment]
不知道你为啥会出现这种错误，复现才能知道

**Comment by peytonzhu** [comment]
我在windows上使用也有这样的报错，而且只能使用默认设置上传一次，以后就上传不了文件了，不知道问题在哪里

**Comment by bazinga-7** [comment]
我也一样

**Comment by aoaostar** [comment]
> 我也一样。
> 正在上传【19379551_234579333715353_4339714404183441408_n.jpg】: 100MB [00:00, ?B/s]
> 这个文件其实只有800k。
> {'code': 'InvalidParameter.ContentHash', 'message': 'The input parameter content_hash is not valid. file content hash is not matched with content_hash in complete file request'}
> 然后跟着这个报错。

文件上传上来，我测试看看吧，我用了这么久都没有

**Comment by bazinga-7** [comment]
![19379551_234579333715353_4339714404183441408_n](https://user-images.githubusercontent.com/76984242/132466101-cd296017-db97-4aaa-9de8-5eac3ce48e77.jpg)
辛苦

**Comment by aoaostar** [comment]
> ![19379551_234579333715353_4339714404183441408_n](https://user-images.githubusercontent.com/76984242/132466101-cd296017-db97-4aaa-9de8-5eac3ce48e77.jpg)
> 辛苦。文件名19379551_234579333715353_4339714404183441408_n.jpg

![image](https://user-images.githubusercontent.com/86001674/132499108-2854f97b-f407-4182-94ae-f9b65291fe9c.png)
刚刚测试了，没有问题

**Comment by aoaostar** [comment]
![image](https://user-images.githubusercontent.com/86001674/132500284-e7e6b5e7-990c-4440-9b77-e938f64fcbf5.png)
![image](https://user-images.githubusercontent.com/86001674/132500314-67720e40-b3bb-4185-abd7-1ec5aea2de6f.png)
我测试了几次都是可以上传的

**Comment by gifyic** [comment]
> 我也一样。
> 正在上传【19379551_234579333715353_4339714404183441408_n.jpg】: 100MB [00:00, ?B/s]
> 这个文件其实只有800k。
> {'code': 'InvalidParameter.ContentHash', 'message': 'The input parameter content_hash is not valid. file content hash is not matched with content_hash in complete file request'}
> 然后跟着这个报错。



> 我在windows上使用也有这样的报错，而且只能使用默认设置上传一次，以后就上传不了文件了，不知道问题在哪里

我是linux

**Comment by gifyic** [comment]
> 我在windows上使用也有这样的报错，而且只能使用默认设置上传一次，以后就上传不了文件了，不知道问题在哪里

我是linux

**Comment by gifyic** [comment]
现在又有个报错{'code': 'ForbiddenDriveLocked', 'message': 'User not authorized to operate on the specified APIs until unlock drive drive is locked'}

**Comment by aoaostar** [comment]
> 现在又有个报错{'code': 'ForbiddenDriveLocked', 'message': 'User not authorized to operate on the specified APIs until unlock drive drive is locked'}

你确定你的配置是正确的？drive_id没改吧

**Comment by QIN2DIM** [comment]
@gifyic 
以下API参考指明了错误的根本原因，`forbidden`缺少操作权限，说明token过期。`invalid parameter` 请求参数错误，个人觉得代码运行过程可能（人为）对资源本身造成污染。

- [OAuth API -- ForbiddenError](https://help.aliyun.com/document_detail/175925.html)
- [OAuth API -- InvalidParameterError](https://help.aliyun.com/document_detail/188259.html#:~:text=string-,InvalidParameterError,-InvalidParameterError%20%E5%8F%82%E6%95%B0%E9%9D%9E%E6%B3%95)
