### ISSUE TITLE
请问为何要设置任务队列，会导致文件更新后无法上传

### ISSUE THREAD

**Issue by spldmanager** [Hidove/aliyundrive-uploader#29]
```
        find = db.table('task').where('filepath=? and realpath=?', (tmp['filepath'], tmp['realpath'],)).find()
        if find:
            print_info('【%s】已存在任务队列中，跳过' % tmp['filepath'])
```
我理解是去查询数据库，该文件是否已经上传了，如果上传过了就直接跳过上传。但是如果这样，文件内容修改了也不上传了吗？不太合理吧
另外如果不是常驻，main.py结束的时候会调用suicide函数，但问题是这个退出函数为什么返回1而不是返回0？返回1会导致bash中该执行结果为失败，影响后续脚本的执行

**Comment by aoaostar** [comment]
你可以修改文件名添加版本号，或者上传时加个sha1校检，对比数据库记录，本身我是用于文件批量上传的，没有修改文件内容的需求，所以没有考虑你这种情况
suicide函数我本身就是用来异常退出的，执行main.py结束后我就懒得另外写退出，直接就用了，用于bash我倒是没有考虑过
感谢反馈
