### ISSUE TITLE
关于应用安全的建议

### ISSUE THREAD

**Issue by QIN2DIM** [Hidove/aliyundrive-uploader#30]
`Aliyundrive`目前版本的Public API控制`TOKEN`，`REFRESH_TOKEN`以及`DRIVE_ID`就能接管一个虚拟实例的操作权限。

建议依然保留`New Token`的配置文件回写行为，但大可不必在运行日志中“完整记录”或"更新"这些敏感参数。

![image](https://user-images.githubusercontent.com/62018067/133892016-d62f2af2-2ea3-43bc-aa0f-127d35158f23.png)

**Comment by aoaostar** [comment]
问题不大

**Comment by aoaostar** [comment]
问题不大
