### ISSUE TITLE
关于应用性能的建议

### ISSUE THREAD

**Issue by QIN2DIM** [Hidove/aliyundrive-uploader#31]
## 建议重写`ACCESS_TOKEN`管理服务

- `Aliyundrive`当前阶段`ACCESS_TOKEN`约每2h刷新一次，而本项目关于`ACCESS_TOKEN`的[管理方案](https://github.com/Hidove/aliyundrive-uploader/commit/b1f2c1189a00b3bc46c6eb1a29b9120ce59be2a8#diff-b10564ab7d2c520cdd0243874879fb0a782862c3c902ab535faabe57d5a505e1R68)似乎并不科学。

- 大概看了一下源码，本人认为本项目的`ACCESS_TOKEN`处于[欠初始化状态](https://github.com/Hidove/aliyundrive-uploader/blob/85553e9500e0c3886a38a4b296f6101c9ebc2967/common.py#L25)。配置文件中只要求开发者（首次）手动获取`DRIVE_ID`和`REFRESH_TOKEN`（然而完全可以手动初始化`ACCESS_TOKEN`因为它们就隔了一行，如README中的截图所示），于是程序运行后（无论`ACCESS_TOKEN`是否真的失效），都会在上传任务正式开始前被重新更新一次，并且在后续长段时间内子线程通过强竞争的方式进行”[倒计时600s](https://github.com/Hidove/aliyundrive-uploader/blob/85553e9500e0c3886a38a4b296f6101c9ebc2967/common.py#L26)被动更新`ACCESS_TOKEN`“的任务。

- 这会引发一系列难以应付的问题，[check_auth()](https://github.com/Hidove/aliyundrive-uploader/blob/85553e9500e0c3886a38a4b296f6101c9ebc2967/AliyunDrive.py#L279)被放置在如“新建网盘目录”等多个核心业务当中。当用户配置多线程下载大量（指向目录的）小文件时，每个“分发线程”都会执行一次`ACCESS_TOKEN`更新请求。

- 此外，`ThreadPoolExecutor(max_workers=None, thread_name_prefix='', initializer=None, initargs=())`在 3.5 版本后，如果 max_workers 为 None 或没有指定，将默认为机器处理器的个数而非1；在3.8版本后则默认启动至少5个核心线程`min(32, os.cpu_count() + 4)`，所以我们可能消耗了成倍的资源的去”计算“更新时间，程序也会在某个时间点频繁更新权限出现“绊脚”的情况。

## 建议使用 Coroutine-Pool 多路复用协程池管理任务队列

> 使用通信共享内存，而不是使用内存通信。

本项目中写满了子线程的竞争行为，这在批量传输小文件时将带来极大的性能损耗。可以使用`gevent`等优秀的协程框架处理密集I/O业务，在虚拟线程阻塞时让出资源，也能更加方便地管理事务回滚以及标记异常实例。

**Comment by aoaostar** [comment]
* `access_token`又臭又长，有了`refresh_token`可以直接获取新的`access_token`，没有必要另外再添加个配置项了
* `access_token`在很久之前的版本中确实会每次上传更新一次，不过早已修复了
https://github.com/Hidove/aliyundrive-uploader/commit/b1f2c1189a00b3bc46c6eb1a29b9120ce59be2a8#diff-00faf9ddca954cb25c8ad342486928312007c387eecaa4c70bcd16cbaaa8cdf8R152-R154
* `check_auth`因为多线程的问题确实会执行一些无意义的刷新，解决方案也简单
https://github.com/Hidove/aliyundrive-uploader/blob/adc9008b3d04c34f2792a258ae0e50016cad02dc/main.py#L56-L59
`max_workers`在小于1的情况下是直接单线程的
https://github.com/Hidove/aliyundrive-uploader/blob/adc9008b3d04c34f2792a258ae0e50016cad02dc/main.py#L67-L76
* 用协程的效率和用线程其实差别不大，批量上传也就同时上传十几个。。。

**Comment by QIN2DIM** [comment]
emmmm......先处理一下`common.py`的bug
https://github.com/Hidove/aliyundrive-uploader/blob/adc9008b3d04c34f2792a258ae0e50016cad02dc/common.py#L19

**Comment by QIN2DIM** [comment]
>   `max_workers`在小于1的情况下是直接单线程的
>   https://github.com/Hidove/aliyundrive-uploader/blob/adc9008b3d04c34f2792a258ae0e50016cad02dc/main.py#L67-L76

可是您的检测线程是通过这种方式提交的
https://github.com/Hidove/aliyundrive-uploader/blob/adc9008b3d04c34f2792a258ae0e50016cad02dc/main.py#L102

**Comment by aoaostar** [comment]
> emmmm......先处理一下`common.py`的bug
> https://github.com/Hidove/aliyundrive-uploader/blob/adc9008b3d04c34f2792a258ae0e50016cad02dc/common.py#L19

这个测试忘了删掉了😂
