### ISSUE TITLE
使用nohup + & 命令运行脚本上传到一半时报错（如图）

### ISSUE THREAD

**Issue by xiaocainiao2020** [Hidove/aliyundrive-uploader#32]
![小Q截图-20210920135143](https://user-images.githubusercontent.com/61716543/133980647-765a4cbd-16da-47ac-ad91-cfe427c5363f.png)

**Comment by aoaostar** [comment]
试试直接运行有没有问题

**Comment by xiaocainiao2020** [comment]
> 试试直接运行有没有问题

试了，也是这样的问题，上传到49%就出这个了。

**Comment by aoaostar** [comment]
可能是网络问题吧，海外机器已经被限制了，上传很慢了

**Comment by xiaocainiao2020** [comment]
> 可能是网络问题吧，海外机器已经被限制了，上传很慢了

不是海外的机器，用的腾讯云上海的，8M的宽带。

**Comment by xiaocainiao2020** [comment]
具体是什么原因呢，这个有办法解决吗，再过几天感觉服务器硬盘要满了

**Comment by aoaostar** [comment]
你多大的文件，我测试一下大文件上传吧

**Comment by xiaocainiao2020** [comment]
> 你多大的文件，我测试一下大文件上传吧

8个G，我阿里云轻量的香港和新加坡都是正常使用的，出问题这个是腾讯云轻量上海的。不知道是和服务器有关还是脚本有关。谢谢作者大大，麻烦了。

**Comment by xiaocainiao2020** [comment]
突然想到一点，再补充一下，出问题这个用的最新版。之前没问题的用的是前一两个版本。

**Comment by aoaostar** [comment]
我上传了20G的文件都没问题，就是速度慢，腾讯云香港轻量，你用的是编译后的还是直接脚本运行的？

**Comment by aoaostar** [comment]
> 突然想到一点，再补充一下，出问题这个用的最新版。之前没问题的用的是前一两个版本。

跟之前版本没关系啊，我这几个版本都没有修改过上传的代码

**Comment by xiaocainiao2020** [comment]
> 我上传了20G的文件都没问题，就是速度慢，腾讯云香港轻量，你用的是编译后的还是直接脚本运行的？

直接脚本运行的。

**Comment by aoaostar** [comment]
贴一下你的配置吧，token啥的不用

**Comment by xiaocainiao2020** [comment]
{"REFRESH_TOKEN": "xxx", "DRIVE_ID": "xxx", "ROOT_PATH": "vps_auto", "FILE_PATH": "/www/wwwroot/bilibili_rec_video/", "MULTITHREADING": false, "MAX_WORKERS": 5, "CHUNK_SIZE": 10485760, "RESUME": false, "OVERWRITE": false, "RETRY": 0, "RESIDENT": false, "ALLOW_REPEAT": false, "VERSIONS": "v2021.0919.2000"}

**Comment by xiaocainiao2020** [comment]
> 贴一下你的配置吧，token啥的不用

{"REFRESH_TOKEN": "xxx", "DRIVE_ID": "xxx", "ROOT_PATH": "vps_auto", "FILE_PATH": "/www/wwwroot/bilibili_rec_video/", "MULTITHREADING": false, "MAX_WORKERS": 5, "CHUNK_SIZE": 10485760, "RESUME": false, "OVERWRITE": false, "RETRY": 0, "RESIDENT": false, "ALLOW_REPEAT": false, "VERSIONS": "v2021.0919.2000"}

**Comment by aoaostar** [comment]
没找到有效的解决办法，上传大文件才有，貌似到5G就会出现，之前没有这种问题，可能是阿里的搞得鬼吧

**Comment by xiaocainiao2020** [comment]
> 没找到有效的解决办法，上传大文件才有，貌似到5G就会出现，之前没有这种问题，可能是阿里的搞得鬼吧

作者大大在测试中也遇到这个问题了吗？

**Comment by aoaostar** [comment]
我找到了解决办法，上传8.97GB的文件成功！你可以试一下
![image](https://user-images.githubusercontent.com/86001674/134616774-a0fbc3ce-f935-4231-a6b9-5244a676e967.png)
![image](https://user-images.githubusercontent.com/86001674/134616795-8e25e74b-fafc-420c-a7b6-d8db2ddb893c.png)
覆盖一下`AliyunDrive.py`的代码，可以的话麻烦回复一下，我好`push`新代码
https://pastebin.ubuntu.com/p/j7cpW7b9yV/

**Comment by xiaocainiao2020** [comment]
> 我找到了解决办法，上传8.97GB的文件成功！你可以试一下
> ![image](https://user-images.githubusercontent.com/86001674/134616774-a0fbc3ce-f935-4231-a6b9-5244a676e967.png)
> ![image](https://user-images.githubusercontent.com/86001674/134616795-8e25e74b-fafc-420c-a7b6-d8db2ddb893c.png)
> 覆盖一下`AliyunDrive.py`的代码，可以的话麻烦回复一下，我好`push`新代码
> https://pastebin.ubuntu.com/p/j7cpW7b9yV/

可以啦，能上传成功了。
不过中间有过两次[Errno 32] Broken pipe，提示上传地址已失效正在获取新的上传地址，然后上传地址刷新成功。这个是正常的吗。

**Comment by aoaostar** [comment]
> > 我找到了解决办法，上传8.97GB的文件成功！你可以试一下
> > ![image](https://user-images.githubusercontent.com/86001674/134616774-a0fbc3ce-f935-4231-a6b9-5244a676e967.png)
> > ![image](https://user-images.githubusercontent.com/86001674/134616795-8e25e74b-fafc-420c-a7b6-d8db2ddb893c.png)
> > 覆盖一下`AliyunDrive.py`的代码，可以的话麻烦回复一下，我好`push`新代码
> > https://pastebin.ubuntu.com/p/j7cpW7b9yV/
> 
> 可以啦，能上传成功了。
> 不过中间有过两次[Errno 32] Broken pipe，提示上传地址已失效正在获取新的上传地址，然后上传地址刷新成功。这个是正常的吗。

是正常的，只能通过重新获取新的上传地址才能继续上传
