### ISSUE TITLE
是否可以跳过文件校检（哈希），直接上传

### ISSUE THREAD

**Issue by lesca** [Hidove/aliyundrive-uploader#35]
现在上传文件前都需要检查文件哈希值，如果云端存在该文件，就会秒传。

我会打包并加密上传的照片，因此每个文件必定是独一无二的，因此希望直接跳过哈希计算，直接上传。

由于每次会上传数百G的文件，浪费CPU也浪费电，浪费煤炭，产生二氧化碳，污染环境。。。（喂扯远了。。）

希望能稍微增加一个配置选项。谢谢！

**Comment by lesca** [comment]
目前我修改了get_hash如下：
```python:
def get_hash(filepath, block_size=2 * 1024 * 1024):
  sha1 = hashlib.sha1()
  return sha1.hexdigest()
 ```
但是还是会产生一个hash，还是会有撞车的可能的吧~

还是希望能在配置文件里直接关掉。谢谢啦

**Comment by lesca** [comment]
@aoaostar 大佬如果可以实现的话 还是加一个吧 譬如备份照片和私人文件的场景 绝大多数数据都是唯一的

**Comment by aoaostar** [comment]
> @aoaostar 大佬如果可以实现的话 还是加一个吧 譬如备份照片和私人文件的场景 绝大多数数据都是唯一的

刚刚测试一下，`sha1`是必须的，而`proof_code`是用于秒传的，你的文件唯一也是没办法的，官方会检查sha1，不一致直接报错
