### ISSUE TITLE
只想上传文件夹下特定后续名的文件应该怎样操作呀？

### ISSUE THREAD

**Issue by ybbluesky** [Hidove/aliyundrive-uploader#37]
本地目录中我只想上传特定文件名，如只想上传rar文件，应该在那儿增加限制文件后缀的代码来控制上传文件呀？谢谢

**Comment by aoaostar** [comment]
你可以通过shell命令实现上传特定类型文件，本身没有这个功能

**Comment by ybbluesky** [comment]
> 你可以通过shell命令实现上传特定类型文件，本身没有这个功能

能在检测到上传文件时判断后缀吗？符合上传，不符合跳过，这代码应加在什么位置？可否告之

**Comment by aoaostar** [comment]
shell遍历指定目录并获取目录下指定后缀的文件
https://blog.csdn.net/waitfor920/article/details/103583873
然后用命令行上传不就得了

**Comment by ybbluesky** [comment]
> shell遍历指定目录并获取目录下指定后缀的文件 https://blog.csdn.net/waitfor920/article/details/103583873 然后用命令行上传不就得了

只会在win下使用，其他的系统不会，py只知一点点

**Comment by lesca** [comment]
common.py 里 `get_all_file` 方法

**Comment by ybbluesky** [comment]
自力更生，大家可改get_all_file_relative
