### ISSUE TITLE
这种报错能否跳过，程序停下来了。

### ISSUE THREAD

**Issue by luolovehk** [Hidove/aliyundrive-uploader#38]
正在上传【0138 - 五一假期带孩子出去玩怎么拍美美的亲子照？.mp4】: 100MB [00:00, ?B/s]
{'code': 'InvalidParameter.ContentHash', 'message': 'The input parameter content_hash is not valid. file content hash is not matched with content_hash in complete file request'}

**Comment by aoaostar** [comment]
计算哈希失败了，是没法继续上传到阿里云盘的啊，你也可以修改check_auth方法
https://github.com/Hidove/aliyundrive-uploader/blob/184fabfc85d70b3cda1badabbe07cf2059f5d8e2/AliyunDrive.py#L341-L355

**Comment by aoaostar** [comment]
计算哈希失败了，是没法继续上传到阿里云盘的啊，你也可以修改check_auth方法
https://github.com/Hidove/aliyundrive-uploader/blob/184fabfc85d70b3cda1badabbe07cf2059f5d8e2/AliyunDrive.py#L341-L355
