### ISSUE TITLE
无法上传？

### ISSUE THREAD

**Issue by lovechang1986** [Hidove/aliyundrive-uploader#40]
之前在另外一个账户可以正常上传，现在我更改另外一个网盘的token和id，弹出如下错误：
`{'code': 'ForbiddenNoPermission.File', 'message': 'No Permission to access resource File'}`

我原以为这是权限问题，因此使用sudo运行main.py,又出现这个错误：
```
Traceback (most recent call last):
  File "/root/.aliup/main.py", line 12, in <module>
    from concurrent.futures import ThreadPoolExecutor
ImportError: No module named concurrent.futures
```

好奇怪呀..`~~

**Comment by aoaostar** [comment]
No Permission to access resource File
可能是你的driveId什么的信息出错了吧
