### ISSUE TITLE
无法以普通用户运行

### ISSUE THREAD

**Issue by yunxinlxsy** [Hidove/aliyundrive-uploader#41]
普通用户会提示权限不足，File "sqlite.py", line 321, in write_lock
    with(open(self.__LOCK, 'w+'))as f:
PermissionError: [Errno 13] Permission denied:可是里面的文件所有者以及权限我都修改了，依然这样

**Comment by aoaostar** [comment]
那就不清楚ヽ(ー_ー)ノ
