### ISSUE TITLE
希望增加一个：上次后删除本地文件的参数

### ISSUE THREAD

**Issue by sw586** [Hidove/aliyundrive-uploader#42]
首先感谢作者 提供这么好的开源插件，辛苦了 谢谢！

就是提个小建议，在上传命令基础上加一个删除本地文件的参数就更完美了，比如：

python3 main.py -d D:\下载\需要转移的\人人商城

d参数：上次后删除本地文件。因为已经上次到网盘本地存在的价值不大。

**Comment by aoaostar** [comment]
这样出现意外的可能性很大，数据珍贵，手动删除较好
