### ISSUE TITLE
”海外机器不能上传“的说法是否有误

### ISSUE THREAD

**Issue by cylind** [Hidove/aliyundrive-uploader#54]
>由于阿里云盘限制了海外，海外机器根本无法上传

我之前都能上传的，刚刚又去随便下了个美剧测试，完全没问题，和以前一样（速度是7MB/s-10MB/s的样子）。下图是我刚下到阿里云盘上的资源
![image](https://user-images.githubusercontent.com/48314862/165939831-872b746d-4c03-4452-889c-c846ea76a1c4.png)

**Comment by aoaostar** [comment]
有些海外机器确实无法上传
刚刚测试了
* buyvm确实是不能上传，几kb每秒
* 搬瓦工是能上传的，速度一般
* 腾讯云香港才100K
* 阿里云自家的新加坡跑满
> 还是有很多人说海外上传不了，可能是限制了但没有完全限制吧

**Comment by cylind** [comment]
可能是和ip有关，不能上传的应该是被判为恶意ip了，（就像不少公共代理有时不能访问谷歌学术一样，甚至访问谷歌都会出人机验证，公共ip访问太频繁了）；速度不佳的应该和vps走的线路有关吧，阿里云盘就只有在北京的服务器吧我记得。

对于不能上传的，我有个小方法不知能不能行，在请求头加上”'X-Forwarded-For': 随机国内ip“，这个方法能绕过一些网站的ip限制检测。

**Comment by lovechang1986** [comment]
我在海外的一个VPS连登录都无法登录：
`PANI[2022-05-19 05:01:02] Post "https://auth.aliyundrive.com/v2/account/token": dial tcp [2408:4001:1000::4]:443: connect: no route to host `
总是弹出这样的错误，哪怕配置和另外一台完全一样，也是无法登录。

于是想着使用阿里云的ECS做代理，能否给一份详细的nginx方向代理配置教程，在readme里只看到location，有点懵，其他的一些配置怎么操作的。。。

**Comment by aoaostar** [comment]
> 我在海外的一个VPS连登录都无法登录： `PANI[2022-05-19 05:01:02] Post "https://auth.aliyundrive.com/v2/account/token": dial tcp [2408:4001:1000::4]:443: connect: no route to host ` 总是弹出这样的错误，哪怕配置和另外一台完全一样，也是无法登录。
> 
> 于是想着使用阿里云的ECS做代理，能否给一份详细的nginx方向代理配置教程，在readme里只看到location，有点懵，其他的一些配置怎么操作的。。。

其他的默认就行了啊，这段直接添加到server里面就行了
