### ISSUE TITLE
视频上传失败怎么办呀

### ISSUE THREAD

**Issue by xiaocainiao2020** [Hidove/aliyundrive-uploader#55]
用了宝塔版本的，也用了原版的，都是刚开始有上传，过一会就失败了。小文件能上传成功，大点的视频就不行了。

**Comment by xiaocainiao2020** [comment]
日志提示 Request has expired.

**Comment by aoaostar** [comment]
已经完美修复了https://github.com/aoaostar/alidrive-uploader/commit/5057ad5976719cda6fa9feb147f7119e4d6eb2c0
