### ISSUE TITLE
上传文件夹/文件存在同名

### ISSUE THREAD

**Issue by mayishidai** [Hidove/aliyundrive-uploader#56]
上传备份文件夹/文件的时候，会出现，原本是一个文件夹的内容，会被分割存放为同名目录的其他文件夹下
![image](https://user-images.githubusercontent.com/20534392/167236417-f1e45e6c-06f6-4dcd-9899-604e2681286f.png)
![image](https://user-images.githubusercontent.com/20534392/167236430-1b08abbf-6e92-4179-8b46-5e59eb7a507c.png)

**Comment by aoaostar** [comment]
该问题应该在该仓库：https://github.com/aoaostar/alidrive-uploader  

https://github.com/aoaostar/alidrive-uploader/commit/60e82f4764b32a14ae2a7035ac08e7efe4a93197

**Comment by aoaostar** [comment]
https://github.com/aoaostar/alidrive-uploader/commit/dca7fcb51385dca1e2b4c7eb7859f8333ad50e2e

**Comment by aoaostar** [comment]
🐛 修复并发下创建相同目录的问题  https://github.com/aoaostar/alidrive-uploader/commit/dca7fcb51385dca1e2b4c7eb7859f8333ad50e2e

**Comment by lovechang1986** [comment]
![Screenshot_20220611145358.jpg](https://user-images.githubusercontent.com/8605164/173177112-70d6a1eb-5e3d-45a3-96a1-b3ae3d544d9b.jpg)

重名问题好像仍然存在？

**Comment by aoaostar** [comment]
> ![Screenshot_20220611145358.jpg](https://user-images.githubusercontent.com/8605164/173177112-70d6a1eb-5e3d-45a3-96a1-b3ae3d544d9b.jpg)
> 
> 重名问题好像仍然存在？

这个解决的是相同目录的问题
操作系统中也不允许存在相同文件的，你用的是宝塔插件，对同一文件提交了多次上传？
如果是这样的话那就没法避免的

**Comment by lovechang1986** [comment]
并没有用宝塔，不太会用，一直crontab定时上传，只是执行了多次命令。其实还是回到有个issue提到了，可否增加-d参数，上传成功删除文件。在没有删除的情况下只能多次上传了....

**Comment by aoaostar** [comment]
> 并没有用宝塔，不太会用，一直crontab定时上传，只是执行了多次命令。其实还是回到有个issue提到了，可否增加-d参数，上传成功删除文件。在没有删除的情况下只能多次上传了....

你是执行了多次命令啊，在shell脚本上控制一下，让它执行完上一次上传才能开始下一次
上传完毕删除文件这个，上传命令后面加一句删除命令就行了，上传工具只做纯粹的上传

**Comment by lovechang1986** [comment]
懂了，可能是一个程序正在执行，到了另一个的启动时间所以会出现重复。我也准备包一层程序并加个文件锁的...谢谢指导
