### ISSUE TITLE
能加断点续传吗？

### ISSUE THREAD

**Issue by ddfiberglass** [Hidove/aliyundrive-uploader#6]
我一个1G的文件从Ubuntu 20.04服务器上传到阿里云网盘老是出错，每次都有重新开始传，错误提示：

pipes-presentation-20210423.mp4正在校检文件中，耗时与文件大小有关
        文件名：11-pipes-presentation-20210423.mp4
        hash：4817bcc8425ac8be2264ff379887a64b0f46e661
        文件大小：1134460273
        文件路径：youtube/11-pipes-presentation-20210423.mp4

检索目录中
目录id获取成功6073f804da645896ab184012afdfd4e0c7fe9ab3
Traceback (most recent call last):
  File "main.py", line 137, in <module>
    if res.result():
  File "/usr/lib/python3.8/concurrent/futures/_base.py", line 432, in result
    return self.__get_result()
  File "/usr/lib/python3.8/concurrent/futures/_base.py", line 388, in __get_result
    raise self._exception
  File "/usr/lib/python3.8/concurrent/futures/thread.py", line 57, in run
    result = self.fn(*self.args, **self.kwargs)
  File "main.py", line 61, in upload_file
    drive.upload(upload_url)
  File "/root/aliyundrive-uploader/AliyunDrive.py", line 117, in upload
    res.raise_for_status()
  File "/usr/local/lib/python3.8/dist-packages/requests/models.py", line 943, in raise_for_status
    raise HTTPError(http_error_msg, response=self)
requests.exceptions.HTTPError: 400 Client Error: Bad Request for url: https://bj29.cn-beijing.data.alicloudccp.com/4oW5G1mH%2F27564%2F6088ab6af27e6944c74c4b0aa509838b6182e85d%2F6088ab6a58520b3afd2b480a8a7b020fa7df8982?Expires=1619573114&OSSAccessKeyId=LTAIsE5mAn2F493Q&Signature=xEewGJ4QSlF1Ir8u7%2Bd0biuKyp4%3D&partNumber=1&uploadId=BD00C9F4C9CF4E2B8C71C5620236BB42

**Comment by zsbai** [comment]
上传30s就出错，我也是这样....

**Comment by Hidove** [comment]
@ddfiberglass 
我尝试了2.14GB的文件上传，发现并没有问题
![image](https://user-images.githubusercontent.com/42663943/116540687-149e5a80-a91d-11eb-8110-e8ba7e957c07.png)
你在`AliyunDrive.py`文件内加上这个然后运行一次看看，看看打印的错误信息
```
print_error(res.content)
```
![image](https://user-images.githubusercontent.com/42663943/116540854-48798000-a91d-11eb-9bdd-81bbe95aed10.png)

**Comment by ddfiberglass** [comment]
我的服务器带宽少，我上传只有100k，上传时间很长（3个小时左右），传到最后老是出问题。

**Comment by Hidove** [comment]
@ddfiberglass 续传okay le，不过是基于分块上传的，上传到了第三块断了，重新上传会继续从第三块开始

**Comment by ddfiberglass** [comment]
> @ddfiberglass 续传okay le，不过是基于分块上传的，上传到了第三块断了，重新上传会继续从第三块开始

非常感谢，我试试看。

**Comment by ddfiberglass** [comment]
> @ddfiberglass 续传okay le，不过是基于分块上传的，上传到了第三块断了，重新上传会继续从第三块开始

正在上传【How to replace PVC, PET and balsa The new SAERfoam® Series.-OZ_zX6gteQQ.mp4】:  86%|##############5  | 102M/119M [1:22:12<13:52, 21.7kB/s]。

传到86%后出错，再次上传还是从0开始上传。我这里好像断点续传好像没起作用。

**Comment by zsbai** [comment]
> > @ddfiberglass 续传okay le，不过是基于分块上传的，上传到了第三块断了，重新上传会继续从第三块开始
> 
> 
> 
> 正在上传【How to replace PVC, PET and balsa The new SAERfoam® Series.-OZ_zX6gteQQ.mp4】:  86%|##############5  | 102M/119M [1:22:12<13:52, 21.7kB/s]。
> 
> 
> 
> 传到86%后出错，再次上传还是从0开始上传。我这里好像断点续传好像没起作用。

需要配置文件打开resume应该

**Comment by Hidove** [comment]
> > > @ddfiberglass 续传okay le，不过是基于分块上传的，上传到了第三块断了，重新上传会继续从第三块开始
> > 
> > 
> > 正在上传【How to replace PVC, PET and balsa The new SAERfoam® Series.-OZ_zX6gteQQ.mp4】:  86%|##############5  | 102M/119M [1:22:12<13:52, 21.7kB/s]。
> > 传到86%后出错，再次上传还是从0开始上传。我这里好像断点续传好像没起作用。
> 
> 需要配置文件打开resume应该

是的，需要启用
