### ISSUE TITLE
1.1GB文件上传出错该怎么解决？用的宝塔插件

### ISSUE THREAD

**Issue by asd519627326** [Hidove/aliyundrive-uploader#63]
显示：“上传失败:AccessToken is invalid.”

**Comment by aoaostar** [comment]
版本和日志  
https://github.com/aoaostar/alidrive-uploader/blob/9a4f7b0bf2a0c0bc11adf0491ed6073c0c4d815f/pkg/alidrive/alidrive.go#L112  
AccessTokenInvalid是会重试的诶😩

**Comment by asd519627326** [comment]
[36mINFO[0m[2022-07-25 06:18:03] 共计1个文件                                       
[36mINFO[0m[2022-07-25 06:18:03] 正在获取AccessToken                              
[36mINFO[0m[2022-07-25 06:18:03] 正在生成目录                                       
[36mINFO[0m[2022-07-25 06:18:04] [视频打包.7z]正在上传                                
[36mINFO[0m[2022-07-25 06:24:46] [视频打包.7z] 已上传 60.00MB, 上传速度 127.00KB/s, 共用时 1m20.632849704s, 5% 
[36mINFO[0m[2022-07-25 06:54:11] [视频打包.7z] 已上传 280.00MB, 上传速度 127.12KB/s, 共用时 1m20.550971782s, 25% 
[36mINFO[0m[2022-07-25 07:28:24] [视频打包.7z] 已上传 560.00MB, 上传速度 126.87KB/s, 共用时 1m20.713033493s, 50% 
[36mINFO[0m[2022-07-25 08:07:08] [视频打包.7z] 已上传 850.00MB, 上传速度 127.28KB/s, 共用时 1m20.454152379s, 75% 
[31mERRO[0m[2022-07-25 08:19:09] [视频打包.7z]上传失败:AccessToken is invalid. AccessTokenExpired 
[36mINFO[0m[2022-07-25 08:19:09] 上传完毕！共计1个文件，失败文件个数：1个，耗时：2h1m5.926774397s    
[插件日志][2022-07-25 08:19:09] chmod 755 "/www/server/panel/plugin/alidrive/core/alidrive" && "/www/server/panel/plugin/alidrive/core/alidrive" --root_path="网盘目录" "//视频打包.7z" /
[插件日志][2022-07-25 08:19:09] resp-length=266726,error=

插件版本  2.2.4，Core 版本  Alidrive Uploader v2.1.3

**Comment by asd519627326** [comment]
> 版本和日志
> 
> https://github.com/aoaostar/alidrive-uploader/blob/9a4f7b0bf2a0c0bc11adf0491ed6073c0c4d815f/pkg/alidrive/alidrive.go#L112
> 
> 
> AccessTokenInvalid是会重试的诶😩

�[36mINFO�[0m[2022-07-25 06:18:03] 共计1个文件
�[36mINFO�[0m[2022-07-25 06:18:03] 正在获取AccessToken
�[36mINFO�[0m[2022-07-25 06:18:03] 正在生成目录
�[36mINFO�[0m[2022-07-25 06:18:04] [视频打包.7z]正在上传
�[36mINFO�[0m[2022-07-25 06:24:46] [视频打包.7z] 已上传 60.00MB, 上传速度 127.00KB/s, 共用时 1m20.632849704s, 5%
�[36mINFO�[0m[2022-07-25 06:54:11] [视频打包.7z] 已上传 280.00MB, 上传速度 127.12KB/s, 共用时 1m20.550971782s, 25%
�[36mINFO�[0m[2022-07-25 07:28:24] [视频打包.7z] 已上传 560.00MB, 上传速度 126.87KB/s, 共用时 1m20.713033493s, 50%
�[36mINFO�[0m[2022-07-25 08:07:08] [视频打包.7z] 已上传 850.00MB, 上传速度 127.28KB/s, 共用时 1m20.454152379s, 75%
�[31mERRO�[0m[2022-07-25 08:19:09] [视频打包.7z]上传失败:AccessToken is invalid. AccessTokenExpired
�[36mINFO�[0m[2022-07-25 08:19:09] 上传完毕！共计1个文件，失败文件个数：1个，耗时：2h1m5.926774397s
[插件日志][2022-07-25 08:19:09] chmod 755 "/www/server/panel/plugin/alidrive/core/alidrive" && "/www/server/panel/plugin/alidrive/core/alidrive" --root_path="网盘目录" "//视频打包.7z" /
[插件日志][2022-07-25 08:19:09] resp-length=266726,error=

插件版本 2.2.4，Core 版本 Alidrive Uploader v2.1.3

**Comment by asd519627326** [comment]
> 版本和日志
> 
> https://github.com/aoaostar/alidrive-uploader/blob/9a4f7b0bf2a0c0bc11adf0491ed6073c0c4d815f/pkg/alidrive/alidrive.go#L112
> 
> 
> AccessTokenInvalid是会重试的诶😩

[36mINFO[0m[2022-07-25 19:32:59] 共计1个文件                                       
[36mINFO[0m[2022-07-25 19:32:59] 正在获取AccessToken                              
[36mINFO[0m[2022-07-25 19:33:00] 正在生成目录                                       
[36mINFO[0m[2022-07-25 19:33:00] [录制-22929560-20220725-144907-255-今天是杜杜.flv]正在上传 
[36mINFO[0m[2022-07-25 19:50:32] [录制-22929560-20220725-144907-255-今天是杜杜.flv] 已上传 140.00MB, 上传速度 126.29KB/s, 共用时 1m21.08589571s, 5% 
[36mINFO[0m[2022-07-25 21:11:25] [录制-22929560-20220725-144907-255-今天是杜杜.flv] 已上传 760.00MB, 上传速度 115.74KB/s, 共用时 1m28.470988268s, 25% 
[36mINFO[0m[2022-07-25 22:52:25] [录制-22929560-20220725-144907-255-今天是杜杜.flv] 已上传 1.49GB, 上传速度 127.00KB/s, 共用时 1m20.62793789s, 50% 
[36mINFO[0m[2022-07-26 00:35:24] [录制-22929560-20220725-144907-255-今天是杜杜.flv] 已上传 2.25GB, 上传速度 126.53KB/s, 共用时 1m20.927857695s, 75% 
[36mINFO[0m[2022-07-26 01:35:27] [录制-22929560-20220725-144907-255-今天是杜杜.flv] 已上传 2.70GB, 上传速度 126.78KB/s, 共用时 1m20.767428063s, 90% 
[36mINFO[0m[2022-07-26 01:55:30] [录制-22929560-20220725-144907-255-今天是杜杜.flv] 已上传 2.85GB, 上传速度 126.88KB/s, 共用时 1m20.708532196s, 95% 
[31mERRO[0m[2022-07-26 02:13:53] [录制-22929560-20220725-144907-255-今天是杜杜.flv]上传失败:The resource part_list is not valid. part entity too small 
[36mINFO[0m[2022-07-26 02:13:53] 上传完毕！共计1个文件，失败文件个数：1个，耗时：6h40m52.948134991s  
[插件日志][2022-07-26 02:13:53] chmod 755 "/www/server/panel/plugin/alidrive/core/alidrive" && "/www/server/panel/plugin/alidrive/core/alidrive" --root_path="网盘目录" "/luboji/22929560-TheMix多语种乐团/录制-22929560-20220725-144907-255-今天是杜杜.flv" /
[插件日志][2022-07-26 02:13:53] resp-length=882244,error=


之前那个问题解决好了，昨天上传3.00GB又出现错误😭，插件版本 2.2.5，Core 版本 Alidrive Uploader v2.1.4

**Comment by aoaostar** [comment]
The resource part_list is not valid. part entity too small  
等我测试一下，看看这是什么问题

**Comment by aoaostar** [comment]
![image](https://user-images.githubusercontent.com/86001674/180904776-9f76c401-dd8e-4f3b-8f32-97389ce1f30a.png)
应该是最后一块小于100k了，这几率也碰到了

**Comment by asd519627326** [comment]
> ![image](https://user-images.githubusercontent.com/86001674/180904776-9f76c401-dd8e-4f3b-8f32-97389ce1f30a.png) 应该是最后一块小于100k了，这几率也碰到了

好吧😂，只要是偶然就行，太倒霉了，这几率也能让我碰上😓

**Comment by aoaostar** [comment]
> > ![image](https://user-images.githubusercontent.com/86001674/180904776-9f76c401-dd8e-4f3b-8f32-97389ce1f30a.png) 应该是最后一块小于100k了，这几率也碰到了
> 
> 好吧😂，只要是偶然就行，太倒霉了，这几率也能让我碰上😓

最后一块是无限制的，不应该存在太小却不行

**Comment by aoaostar** [comment]
![1658981161978](https://user-images.githubusercontent.com/86001674/181419781-12cf1ef0-ebf2-4fd6-ac02-281e4e8e657a.jpg)
![1658981161969](https://user-images.githubusercontent.com/86001674/181419791-f6d1d663-54e1-4dc2-80e2-89b11d9e5c7b.jpg)  
应该是`no problem`了
