### ISSUE TITLE
use staticly-linked binary for arm64

### ISSUE THREAD

**Issue by dobefore** [Hidove/aliyundrive-uploader#64]
Hi,this is a great project that provide us much convenience.Thanks for the work.
Is it possible to link library statically to allow for wider Compatibility？
I cannot manage to run it on Android termux.

**Comment by aoaostar** [comment]
Since the Linux in Android is not so “standard”.
You can download the source code and compile it yourself.
```
GOOS=android
GOARCH=arm64
go build
```
