### ISSUE TITLE
宝塔插件上传命令

### ISSUE THREAD

**Issue by asd519627326** [Hidove/aliyundrive-uploader#65]
再打扰一下,,ԾㅂԾ,,，因为我上传文件比较多，一个一个手动上传太过麻烦，所以我打算写个python脚本自动上传，但是我不知道如何调用这个宝塔插件，希望你能告诉我一下这个插件上传文件命令，我用的系统是debian，麻烦你了

**Comment by aoaostar** [comment]
```
Usage:
  alidrive.exe [OPTIONS] LocalPath RemotePath

Application Options:
  -d, --debug          Debug模式
  -t, --transfers=     同时上传文件个数
  -c, --config=        配置文件路径 (default: config.yaml)
  -p, --proxy=         API代理
  -m, --match_pattern= 正则过滤
  -v, --version        输出版本信息
      --drive_id=      驱动id
      --refresh_token= 刷新令牌
      --root_path=     根目录路径

Help Options:
  -h, --help           Show this help message

Arguments:
  LocalPath:           本地文件路径
  RemotePath:          远程文件路径
```

**Comment by asd519627326** [comment]
> --root_好的，谢谢

**Comment by asd519627326** [comment]
> ```
> Usage:
>   alidrive.exe [OPTIONS] LocalPath RemotePath
> 
> Application Options:
>   -d, --debug          Debug模式
>   -t, --transfers=     同时上传文件个数
>   -c, --config=        配置文件路径 (default: config.yaml)
>   -p, --proxy=         API代理
>   -m, --match_pattern= 正则过滤
>   -v, --version        输出版本信息
>       --drive_id=      驱动id
>       --refresh_token= 刷新令牌
>       --root_path=     根目录路径
> 
> Help Options:
>   -h, --help           Show this help message
> 
> Arguments:
>   LocalPath:           本地文件路径
>   RemotePath:          远程文件路径
> ```

好的，谢谢
