### ISSUE TITLE
海外上传阿里

### ISSUE THREAD

**Issue by miku8311** [Hidove/aliyundrive-uploader#67]
请问配置如何写
ali_drive:
  drive_id: xxx
  refresh_token: xxx
  root_path: 云盘
debug: false
retry: 3
transfers: 3
proxy: location /{
  if ($request_uri ~ /){
    add_header content-type "application/json";
    return 200 "{\"usage\":\"Host/{URL}\"}";
  }
  if ($request_uri ~ ^/(.*)){
    set $proxy_url $1;
  }
  proxy_pass $proxy_url;
  resolver 8.8.8.8;
}

这样写吗？我测试好像没有提速 大佬帮忙看看

**Comment by aoaostar** [comment]
那是nginx配置，配置好后填域名到配置文件里的proxy项中
