### ISSUE TITLE
请问在计算节点上提交任务不能跑是什么原因？

### ISSUE THREAD

**Issue by Ranshan567** [Hidove/aliyundrive-uploader#69]
由于公用服务器不能在登录节点上跑，提交到计算节点后提示错误，不能跑。有没有办法解决？

**Comment by Ranshan567** [comment]
INFO[2022-12-05 11:20:43] 共计1个文件                                       
INFO[2022-12-05 11:20:43] 正在获取AccessToken                              
PANI[2022-12-05 11:20:43] Post "https://auth.aliyundrive.com/v2/account/token": dial tcp: lookup auth.aliyundrive.com on 8.8.8.8:53: dial udp 8.8.8.8:53: connect: network is unreachable 
panic: (*logrus.Entry) 0xc000206460

**Comment by aoaostar** [comment]
https://www.google.com/search?q=connect%3A+network+is+unreachable
