### ISSUE TITLE
新功能建议：添加文件覆盖

### ISSUE THREAD

**Issue by zsbai** [Hidove/aliyundrive-uploader#7]
阿里云上传重复文件会自动在后面加日期，希望加一个功能可以把源文件覆盖掉而不是加日期

**Comment by Hidove** [comment]
![image](https://user-images.githubusercontent.com/42663943/118349476-7b5d7e00-b583-11eb-9f70-196a8010be13.png)
把auto_rename改成refuse试试看吧

**Comment by Hidove** [comment]
不过这样只会跳过不会覆盖

**Comment by zsbai** [comment]
我写了个自动编译文件的action，编译完自动上传到阿里云盘，但是每次编译文件名称都一样嘛，所以都会自动加一个后缀而不是覆盖，我记得是有token就可以任意修改网盘内文件了，所以想到是可以删掉重名文件再上传...?

**Comment by Hidove** [comment]
> 我写了个自动编译文件的action，编译完自动上传到阿里云盘，但是每次编译文件名称都一样嘛，所以都会自动加一个后缀而不是覆盖，我记得是有token就可以任意修改网盘内文件了，所以想到是可以删掉重名文件再上传...?

我刚刚试了一下，只能改成ignore，改成refuse会出错
改成ignore的话，网盘就会存在重名的文件
所以按你的要求的话就只能改成refuse，然后根据返回值中的`'exist': True`然后删除原来的文件再执行一次上传

**Comment by zsbai** [comment]
emmmmm可以实现么？不会要很麻烦吧...

**Comment by Hidove** [comment]
> emmmmm可以实现么？不会要很麻烦吧...

我没有写删除的函数，你可以自己添加

**Comment by zsbai** [comment]
好吧.....我python写的不好，等到暑假我试着写一下

**Comment by Hidove** [comment]
> 好吧.....我python写的不好，等到暑假我试着写一下

已经支持了
       _
      (_)          _
  _         .=.   (_)
 (_)   _   //(`)_
      //`\/ |\ 0`\\
      ||-.\_|_/.-||
      )/ |_____| \(    _
     0   #/\ /\#  0   (_)
        _| o o |_
 _     ((|, ^ ,|))
(_)     `||\_/||`
         || _ ||      _
         | \_/ |     (_)
     0.__.\   /.__.0
      `._  `" `  _.'
         / ;  \ \
       0'-' )/`'-0
           0`

**Comment by zsbai** [comment]
> > 好吧.....我python写的不好，等到暑假我试着写一下
> 
> 已经支持了
> 
> ```
>        _
>       (_)          _
>   _         .=.   (_)
>  (_)   _   //(`)_
>       //`\/ |\ 0`\\
>       ||-.\_|_/.-||
>       )/ |_____| \(    _
>      0   #/\ /\#  0   (_)
>         _| o o |_
>  _     ((|, ^ ,|))
> (_)     `||\_/||`
>          || _ ||      _
>          | \_/ |     (_)
>      0.__.\   /.__.0
>       `._  `" `  _.'
>          / ;  \ \
>        0'-' )/`'-0
>            0`
> ```

感谢～

**Comment by zsbai** [comment]
有一个奇怪的问题，好像只能使用网页端token，手机端token会直接提示token过期，但我在其他的例如alist上可以正常使用；因为网页的token时效非常短，app的token基本上很长时间才会过期

**Comment by Hidove** [comment]
> 有一个奇怪的问题，好像只能使用网页端token，手机端token会直接提示token过期，但我在其他的例如alist上可以正常使用；因为网页的token时效非常短，app的token基本上很长时间才会过期

这个不用担心，只要你在用就不会失效，脚本运行时会自动更新token手机端的token不一样吗？我没有试过

**Comment by zsbai** [comment]
我现在主要在GitHub action上用，token写在secret里面，所以没发现有自动更新...不好意思哈
手机抓的token写在配置文件里会直接提示token已过期，好像web和app的token确实不太一样...具体哪里其实我也没发现emmmm
