### ISSUE TITLE
建议增加日志功能

### ISSUE THREAD

**Issue by xiatao** [Hidove/aliyundrive-uploader#70]
首先非常感谢作者的无私分享，这个项目相当实用好用，我也非常有需求。相比Rclone机械性的上传，这个项目最大优势是支持秒传，我现在主要是利用qbittorrent下载完成后调用这个项目上传下载完的文件至阿里云盘，由于该过程均在VPS后台运行，故希望增加日志功能，便于时候查看上传的具体情况，最后再次致敬！

**Comment by aoaostar** [comment]
这个是有日志记录的
